### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by Huster-Hq** [weijun-arc/BoxPolyp#1]
Could you please provide the download link of your model's prediction results (predicted mask of Polyp-PVT)?

**Comment by weijun-arc** [comment]
Predicted results have been saved in the folder `evaluate/prediction`

**Comment by Huster-Hq** [comment]
Are the results binary or values between 0 and 1?

**Comment by weijun-arc** [comment]
binary

**Comment by Huster-Hq** [comment]
OK! Thanks!
